// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/apis/v2/rpc.proto

package v2

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/googleapis/google/rpc"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ValidateStreamRequest) Validate() error {
	if this.GetRequestUnion() == nil {
		return github_com_mwitkow_go_proto_validators.FieldError("RequestUnion", fmt.Errorf("one of the fields must be set"))
	}
	if oneOfNester, ok := this.GetRequestUnion().(*ValidateStreamRequest_CreateRequest); ok {
		if oneOfNester.CreateRequest != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.CreateRequest); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CreateRequest", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequestUnion().(*ValidateStreamRequest_CancelRequest); ok {
		if oneOfNester.CancelRequest != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.CancelRequest); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CancelRequest", err)
			}
		}
	}
	if oneOfNester, ok := this.GetRequestUnion().(*ValidateStreamRequest_ProxyResponse); ok {
		if oneOfNester.ProxyResponse != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ProxyResponse); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ProxyResponse", err)
			}
		}
	}
	return nil
}
func (this *ValidateStreamCreateRequest) Validate() error {
	if this.Name == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must not be an empty string`, this.Name))
	}
	return nil
}
func (this *ValidateStreamCancelRequest) Validate() error {
	if this.Name == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must not be an empty string`, this.Name))
	}
	return nil
}
func (this *ProxyValidateResponse) Validate() error {
	if nil == this.Proxy {
		return github_com_mwitkow_go_proto_validators.FieldError("Proxy", fmt.Errorf("message must exist"))
	}
	if this.Proxy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Proxy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Proxy", err)
		}
	}
	return nil
}
func (this *ValidateStreamResponse) Validate() error {
	if this.GetResponseUnion() == nil {
		return github_com_mwitkow_go_proto_validators.FieldError("ResponseUnion", fmt.Errorf("one of the fields must be set"))
	}
	if oneOfNester, ok := this.GetResponseUnion().(*ValidateStreamResponse_CreateResponse); ok {
		if oneOfNester.CreateResponse != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.CreateResponse); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CreateResponse", err)
			}
		}
	}
	if oneOfNester, ok := this.GetResponseUnion().(*ValidateStreamResponse_CancelResponse); ok {
		if oneOfNester.CancelResponse != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.CancelResponse); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CancelResponse", err)
			}
		}
	}
	if oneOfNester, ok := this.GetResponseUnion().(*ValidateStreamResponse_ProxyRequest); ok {
		if oneOfNester.ProxyRequest != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ProxyRequest); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ProxyRequest", err)
			}
		}
	}
	return nil
}
func (this *ValidateStreamCreateResponse) Validate() error {
	if this.Name == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must not be an empty string`, this.Name))
	}
	if this.Status != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Status); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Status", err)
		}
	}
	return nil
}
func (this *ValidateStreamCancelResponse) Validate() error {
	if this.Name == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must not be an empty string`, this.Name))
	}
	if this.Status != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Status); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Status", err)
		}
	}
	return nil
}
func (this *ProxyValidateRequest) Validate() error {
	if this.Validator == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Validator", fmt.Errorf(`value '%v' must not be an empty string`, this.Validator))
	}
	if this.ProxyAddr == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ProxyAddr", fmt.Errorf(`value '%v' must not be an empty string`, this.ProxyAddr))
	}
	return nil
}
func (this *GetProxyRequest) Validate() error {
	if this.Validator == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Validator", fmt.Errorf(`value '%v' must not be an empty string`, this.Validator))
	}
	return nil
}
func (this *DeleteProxyRequest) Validate() error {
	if nil == this.Proxy {
		return github_com_mwitkow_go_proto_validators.FieldError("Proxy", fmt.Errorf("message must exist"))
	}
	if this.Proxy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Proxy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Proxy", err)
		}
	}
	return nil
}
