// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/apis/v2/types.proto

package v2

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Proxy) Validate() error {
	if this.Validator == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Validator", fmt.Errorf(`value '%v' must not be an empty string`, this.Validator))
	}
	if this.Addr == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Addr", fmt.Errorf(`value '%v' must not be an empty string`, this.Addr))
	}
	return nil
}
